Add details for subscriber example. Closes #36
KxSystems/javakdb pull request #40
Opened 2020-11-02 17:08 UTC by sshanks-kx

2020-11-05 12:07 UTC, mshimizu-kx requested changes

2020-11-05 12:07 UTC, mshimizu-kx commented on README.md
> +- a KDB+ server running on port 5010 on your machine. The instance must have the .u.sub function defined. See this [knowledge base article](https://code.kx.com/q/kb/publish-subscribe/) for details.
a KDB+ server (tickerplant process) running on port 5010 on your machine. The example of presumed `.u.sub` is found in [KxSystems/kdb-tick](https://github.com/KxSystems/kdb-tick) which is a example tickerplant code. You can run this tickerplant process by
```
tick]$ q tick.q
```
The default port is set 5010 in the startup.

2020-11-05 15:59 UTC, sshanks-kx commented
change made due to suggestion

2020-11-06 23:07 UTC, awilson-kx approved these changes
This is ok with me.

Technically, the startup line `q tick.q` will only work if a schema is predefined in `tick/sym.q` (or in another file, provided as a startup param), but I think that's probably too much detail for what we're doing here.

2020-11-07 20:04 UTC, merged