Improved javadocs & add source/docs to installs. Ref: #41
KxSystems/javakdb pull request #43
Opened 2020-11-04 18:01 UTC by sshanks-kx

2020-11-06 23:11 UTC, awilson-kx requested changes
Small typo

2020-11-06 23:11 UTC, awilson-kx commented on src/main/java/kx/c.java
> +     * @param msgType The type of the message receivedv (0 – async, 1 – sync, 2 – response)
receivedv ->  received

2020-11-07 20:04 UTC, sshanks-kx commented
Typo fixed

2020-11-09 12:54 UTC, mshimizu-kx approved these changes
Confirmed typo fix

2020-11-09 13:04 UTC, merged